# Generated by Django 4.2.24 on 2026-09-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='faq',
            name='faq_type',
            field=models.CharField(db_index=True, default='general', max_length=40),
        ),
        migrations.AddField(
            model_name='faq',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=12),
        ),
        migrations.AlterField(
            model_name='knowledgesource',
            name='faq_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
