# Generated by Django 4.2.24 on 2026-09-22 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge', '0002_alter_chatmessage_options_faq_faq_type_faq_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_sources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='ready', max_length=12),
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['faq_type'], name='knowledge_f_faq_typ_5bc276_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['source', 'faq_type'], name='knowledge_f_source__568792_idx'),
        ),
    ]
