# Generated by Django 4.2.24 on 2026-09-23 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def assign_uncategorized_products(apps, schema_editor):
    Category = apps.get_model('store', 'Category')
    Product = apps.get_model('store', 'Product')
    category, _ = Category.objects.get_or_create(
        slug='uncategorized',
        defaults={'name': 'Uncategorized', 'active': True},
    )
    Product.objects.filter(category__isnull=True).update(category=category)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_coupon_orderstatushistory_payment_productvariant_and_more'),
    ]

    operations = [
        migrations.RunPython(assign_uncategorized_products, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.category'),
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.IntegerField()),
                ('stock_after', models.PositiveIntegerField()),
                ('reason', models.CharField(default='manual_adjustment', max_length=160)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='store.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='store.productvariant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
